---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: sixpack
data:
  nginx.conf: |-
    events {
      worker_connections  1024;
    }
    http {
      server {
        listen 80;
        server_name _;
        location / {
          proxy_pass       http://localhost:5001;
          proxy_set_header Host            $host;
          proxy_set_header X-Forwarded-For $remote_addr;
        }
      }
    }
