---
apiVersion: v1
kind: Service
metadata:
  name: sixpack
  namespace: sixpack
  labels:
    app: sixpack
spec:
  type: NodePort
  ports:
  - name: sixpack-server
    targetPort: 5000
    port: 5000
    nodePort: 31000
  - name: sixpack-web
    targetPort: 80
    port: 80
    nodePort: 31001
  selector:
    app: sixpack
